### ISSUE TITLE
Minor release

### ISSUE THREAD

**Issue by lukesneeringer** [typed-immutable/typed-immutable#30]
@stutrek @davecoates @udnisap 

I have gone through today and tried to do "low hanging fruit" things, and move along the pull requests. We now only have three that are active, and two should be merged soon. Once #18 and #29 are merged, which can hopefully be in a couple of days, I would like to do a release.

I will write up a changelog and such and make a pull request beforehand, so everyone will be able to see it. Does anyone have any objections to this?

**Comment by davecoates** [comment]
Sounds good. 

Thanks for your work! 👍

**Comment by udnisap** [comment]
Great!
Let me know If I can help

**Comment by lukesneeringer** [comment]
Nah, I'll do this one manually, and we will figure out the auto-versioning stuff that you mentioned in #28 afterwards. There are enough fixes and quality of life improvements that I think it would be useful to "just ship it".

**Comment by stutrek** [comment]
@lukesneeringer I'm getting you a beer next time in in TX

**Comment by lukesneeringer** [comment]
Wine or cider, please. :-)

**Comment by lukesneeringer** [comment]
The release PR is up (#33). It will have to go without the enum support for now.
That is fine; it is easy enough for others to write, and we can put out an 0.0.9 later with it.
