### ISSUE TITLE
setSize may only downsize

### ISSUE THREAD

**Issue by manovagyanik1** [typed-immutable/typed-immutable#35]
While using this library with immutable-js, we are encountering a typedError "setSize may only downsize".
But there could be cases in which list size might increase. Why there is this restriction of downsize?

**Comment by davecoates** [comment]
I'm assuming this was done as if you increase the size the elements would only be valid if they were a `Maybe` type, eg. if you had a `List(Number)` and you increase it's size then all new elements would not be valid numbers.

**Comment by manovagyanik1** [comment]
Thanks for quick response.
So in function function mergeIntoListWith(list, merger, iterables) {
  var iters = [];
  var maxSize = 0;
  for (var ii = 0; ii < iterables.length; ii++) {
    var value = iterables[ii];
    var iter = IndexedIterable(value);
    if (iter.size > maxSize) {
      maxSize = iter.size;
    }
    if (!isIterable(value)) {
      iter = iter.map(v => fromJS(v));
    }
    iters.push(iter);
  }
  **if (maxSize > list.size) {
    list = list.setSize(maxSize);
  }**
  return mergeIntoCollectionWith(list, merger, iters);
}

setSize is called to increase the size of the list (immutable-js).

But in typed-immutable setSize is restricting upsize. 
  **setSize(size) {
    if (size > this.size) {
      throw TypeError(`setSize may only downsize`)
    }**

    return change(this, store => store.setSize(size))
  }

I am a bit confused on how both are supposed to work together.

**Comment by davecoates** [comment]
Ah - so this is when you attempt to merge two lists?

I think we will have to implement a custom merge function on `List` to handle this

**Comment by manovagyanik1** [comment]
Any rough timeline for this? We are facing issues because of this. Obviously, we will do some workarounds for now.
