### ISSUE TITLE
Support for Map

### ISSUE THREAD

**Issue by davecoates** [typed-immutable/typed-immutable#9]
I noticed there seems to be support for Map but it's not documented anywhere and has to be imported from 'typed-immutable/lib/map'. Any reason for that (ie. experimental, has issues)?

**Comment by majnu-campact** [comment]
+1 Support for Map would be very convenient!

**Comment by Gozala** [comment]
Yeah map was under construction but somehow escaped my computer and got on github and npm :)
https://twitter.com/gozala/status/641419443889836032

Unfortunately it is not complete as I have not yet wrote tests & had being occupied with other work. If someone would like to take a stab at completing it I'd be more than happy to give a guidance.

**Comment by davecoates** [comment]
I had a brief look through the code but was a bit lost as to how it all worked. If you could give some guidance and maybe an explanation of how things work in general I'll give it a shot.

**Comment by Gozala** [comment]
@davecoates sure I'm more than happy to. The general idea is to put a second layer on top of Immutable.js data structures that do several things:

1. Inherit from a untyped data structure from Immutable.js (see https://github.com/Gozala/typed-immutable/blob/master/src/map.js#L71-L74) which basically provides data structures with all the methods that equivalent structures in Immutable.js have.

2. Data structures implement "type reader" interface (see https://github.com/Gozala/typed-immutable/blob/master/src/map.js#L103-L143) that is pretty much a single function that given a data structure produces either structure compatible with type it represents or a TypeError instance.

3. All typed structure have internal sub-type also implementing "type reader" interface for reading individual entries. In case of Map it is [`EntryType`](https://github.com/Gozala/typed-immutable/blob/master/src/map.js#L18-L42) that is [constructed out of key and value type descriptors](https://github.com/Gozala/typed-immutable/blob/master/src/map.js#L225-L249) during map type definition.

4. All typed data structures are basically wrappers around same data structure from immutable.js, in fact they store that non typed immutable.js data structure under `this[$store]` property.

5. Immutable.js data structures have few primary functions, all others just use those primary functions under the hood. Typed versions just override those primary functions to either directly proxy to `this[$store]` (on read operations) or proxy results of reading value via it's entries type reader to ensure type compatibility (see https://github.com/Gozala/typed-immutable/blob/master/src/map.js#L177-L179 & https://github.com/Gozala/typed-immutable/blob/master/src/map.js#L89-L98)  

6. There is also type inferred versions of data structures to support mapping operations as described in #11 which basically uses special type for entries that never fails just collects type information during construction and at the end of operation type-inferred data structure is finalized by making collected type information be a an actual type information of the result. You can see how it's used in [List](https://github.com/Gozala/typed-immutable/blob/master/src/list.js#L260-L278) and it's pretty much how it supposed to work for map as well but looks like I have not got to it yet.

**Comment by Gozala** [comment]
If you have any more questions let me know I'm happy to help.

**Comment by davecoates** [comment]
I've started on this here:

https://github.com/davecoates/typed-immutable/tree/map

Added test cases including failing cases for map and filter (the original value is changed when map / filter applied) but that's as far as I've got so far

**Comment by pcardune** [comment]
@davecoates looking forward to seeing your results!

**Comment by kabalage** [comment]
+1 I would like use Maps too.

**Comment by Gozala** [comment]
Unfortunately I am no longer able to maintain this project, I apologize. If someone wishes to step up and take leadership of this project please respond to #21
